name: tensorflow_gpu
channels:
     - defaults
     - conda-forge
dependencies:
     - python=3.7
     - cudatoolkit=11.2
     - cudnn=8.1.0
     - ipykernel
     - pip
     - pip:
            - protobuf
            - numpy==1.19.*
            - tensorflow==2.6.*
            - tensorflow-gpu==2.6.*
            - segmentation_models==1.0.1
            - albumentations
            - matplotlib
            - tqdm
variables:
     LD_LIBRARY_PATH: "'$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/'"
     #XLA_FLAGS: "'--xla_gpu_cuda_data_dir=$CONDA_PREFIX/lib/'